### ISSUE TITLE
Error when starting application

### ISSUE THREAD

**Issue by CONandFish** [RiiConnect24/RiiTag-RPC#42] opened 2024-03-01 20:47 UTC
When I started running the application for Windows, it would load then after a moment it would display an error saying "Press ENTER to continue". After pressing enter it just repeats/creates a new error and doesn't go back to the application. I did notice that it says "None" and "0" on the left hand side. Here's a screenshot of the error:
![image](https://github.com/RiiConnect24/RiiTag-RPC/assets/84649317/27e49b7e-8e70-41bb-88c9-ab8d3b1e313a)

**Comment by malmeloo** [comment] 2024-03-02 14:12
I cannot reproduce this issue, but I'm also not using Windows.
- Are you using the binary from the release page or did you clone the repository yourself?
- Has the program worked before? If yes, when? (roughly)
- Are you using the latest version (v1.3.4)? If not, please update first.
- Are there any files in `C:\Users\{username}\AppData\Local\riitag-rpc`? If yes, please post the contents of the `_uid` file in this thread.

**Comment by CONandFish** [comment] 2024-03-02 15:45
I am using the release .exe
It has never worked for me except to login
Yes I am using v1.3.4 (And I tried the second latest version after it started glitching)
Contents of _uid file: a8f90822-5675-4417-9c10-9c95d5089589
Here's my riitag link: https://tag.rc24.xyz/user/808421565309648986

**Comment by malmeloo** [comment] 2024-03-02 19:22
This is due to the ampersand in your username which is breaking the parser. I've just pushed a fix for this, new release will be up in a few minutes.

**Closed** 2024-03-02 19:22 UTC
Labels: bug

**Comment by CONandFish** [comment] 2024-03-02 19:28
Okay thanks

**Comment by malmeloo** [comment] 2024-03-02 19:33
Release is now up: https://github.com/RiiConnect24/RiiTag-RPC/releases/tag/v1.3.5

Let me know if it works!
