### ISSUE TITLE
No Icon on Rich Presence

### ISSUE THREAD

**Issue by KaitheFoox** [RiiConnect24/RiiTag-RPC#44] opened 2024-03-18 20:26 UTC
I can't figure out why the Rich Presence won't display the Icon of the Game I am playing. All I get is a "?" Icon. I thought it was intentional until I saw it worked fine for someone else. 
<img width="307" alt="Screenshot 2024-03-18 at 16 25 45" src="https://github.com/RiiConnect24/RiiTag-RPC/assets/117043441/bade1961-6cbf-4511-aa9e-4f99f1a6edd7">

**Comment by malmeloo** [comment] 2024-03-18 20:46
That means the program is unable to find a working cover or disc image to show. It will almost always find it automatically, but the resolver is quite dumb so there exist edge cases where it will break.

It is possible that this is a temporary network issue on your side. If the program has no network connection the resolver will fail and fall back to the question mark you're seeing now. If you haven't done so already you could try to restart the program.

If it still doesn't work after a restart, can you send me a link to your RiiTag? I will look into it today or tomorrow and figure out what the issue is.

**Comment by KaitheFoox** [comment] 2024-03-18 20:58
It's just always been like this, even when I'm online. I'll leave my RiiTag below.

<a href="https://tag.rc24.xyz/user/442227113597337602"><img src="https://tag.rc24.xyz/442227113597337602/tag.png" alt="RiiTag" /></a>

**Comment by malmeloo** [comment] 2024-03-19 22:54
This turned out to be a silly typo causing all `US` and `JA`-regioned game arts to be non-resolvable. It has been fixed in the latest release, which is uploading as we speak. Let me know if it works!

**Closed by malmeloo** 2024-03-19 22:54 UTC
